# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuskDownPlunge
                                 A QGIS plugin
 Busk down plunge
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-16
        copyright            : (C) 2026 by Mitchell McMillan
        email                : mitchellmcm27@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Mitchell McMillan'
__date__ = '2026-03-16'
__copyright__ = '(C) 2026 by Mitchell McMillan'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BuskDownPlunge class from file BuskDownPlunge.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .busk_down_plunge import BuskDownPlungePlugin
    return BuskDownPlungePlugin()
